# Generated by Django 2.2 on 2020-07-13 14:04

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='类型名称')),
            ],
            options={
                'verbose_name': '博客文章类型',
                'verbose_name_plural': '博客文章类型',
                'db_table': 'type',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('pwd', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, unique=True, verbose_name='标题')),
                ('content', tinymce.models.HTMLField(verbose_name='内容')),
                ('pubtime', models.DateTimeField(verbose_name='时间')),
                ('pic', models.ImageField(null=True, upload_to='', verbose_name='图片')),
                ('type', models.ManyToManyField(to='blog.Type', verbose_name='所属类型')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.User', verbose_name='用户')),
            ],
            options={
                'verbose_name': '博客文章',
                'verbose_name_plural': '博客文章',
                'db_table': 'article',
            },
        ),
    ]
